# Generated by Django 3.0 on 2023-05-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
