# Generated by Django 3.0 on 2023-05-06 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20230506_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='discription',
            new_name='description',
        ),
    ]
