# Generated by Django 3.0 on 2022-08-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20220815_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='current_user_request',
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.png', upload_to='image/profile/2022-08-15-03:05:48.553584'),
        ),
    ]
