# Generated by Django 3.0 on 2022-08-15 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20220815_0305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'ordering': ['-request_date']},
        ),
        migrations.AddField(
            model_name='friend',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.png', upload_to='image/profile/2022-08-15-06:40:47.563390'),
        ),
    ]
