# Generated by Django 4.2.1 on 2023-08-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20220813_1643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp',
        ),
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(upload_to='images/post/'),
        ),
    ]
