# Generated by Django 3.0 on 2022-08-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220813_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/profile/2022-08-13-16:43:25.473212'),
        ),
    ]
