# Generated by Django 3.0 on 2022-08-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20220814_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='image/profile/2022-08-15-01:35:42.922330'),
        ),
    ]
