# Generated by Django 3.0 on 2022-08-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20220815_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='image/profile/2022-08-15-01:47:02.330296'),
        ),
    ]
